use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use crate::worldline::types::{ActorId, FieldKey};

/// A single field change within a WorldStateDelta.
/// Stored as a flat struct for clean JSON serialization (BTreeMap<FieldKey, f64>
/// cannot serialize to JSON because FieldKey is not a string).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FieldChange {
    pub region: String,
    pub domain: String,
    pub delta: f64,
}

impl FieldChange {
    pub fn from_field_key(key: &FieldKey, delta: f64) -> Self {
        Self {
            region: key.region.clone(),
            domain: key.domain.clone(),
            delta,
        }
    }

    pub fn to_field_key(&self) -> FieldKey {
        FieldKey {
            region: self.region.clone(),
            domain: self.domain.clone(),
        }
    }
}

/// A delta describing how the world state changed in a single tick.
/// Generated by the Referee after each simulation round.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorldStateDelta {
    pub tick: u64,
    pub summary: String,
    pub field_changes: Vec<FieldChange>,
    pub affected_actors: Vec<ActorId>,
}

/// Generate a WorldStateDelta for the given tick from agent actions.
/// In Phase 2.4 this is a stub — produces a synthetic delta based on
/// the number of agents and their action types.
pub fn generate_delta(
    tick: u64,
    agent_ids: &[ActorId],
    action_types: &[String],
) -> WorldStateDelta {
    let mut field_changes_map: BTreeMap<(String, String), f64> = BTreeMap::new();

    // Stub: assign small deltas based on action type keywords
    for action_type in action_types {
        let delta_value = match action_type.as_str() {
            s if s.contains("military") || s.contains("exercise") => 1.5,
            s if s.contains("sanctions") || s.contains("counter") => 0.8,
            s if s.contains("diplomatic") || s.contains("protest") => 0.5,
            s if s.contains("negotiation") || s.contains("talks") => -0.3,
            _ => 0.1,
        };

        let domain = if action_type.contains("military") || action_type.contains("exercise") {
            "conflict"
        } else if action_type.contains("diplomatic") || action_type.contains("protest") {
            "diplomacy"
        } else if action_type.contains("sanctions") || action_type.contains("counter") {
            "economy"
        } else if action_type.contains("negotiation") || action_type.contains("talks") {
            "diplomacy"
        } else {
            "economy"
        };

        *field_changes_map
            .entry(("global".to_string(), domain.to_string()))
            .or_insert(0.0) += delta_value;
    }

    let field_changes: Vec<FieldChange> = field_changes_map
        .into_iter()
        .map(|((region, domain), delta)| FieldChange {
            region,
            domain,
            delta,
        })
        .collect();

    let summary = if field_changes.is_empty() {
        "No significant field changes".to_string()
    } else {
        let top_change = field_changes
            .iter()
            .max_by(|a, b| {
                let va = if a.delta >= 0.0 { a.delta } else { -a.delta };
                let vb = if b.delta >= 0.0 { b.delta } else { -b.delta };
                va.partial_cmp(&vb).unwrap_or(std::cmp::Ordering::Equal)
            })
            .unwrap();
        format!(
            "Field shifts in {} domain during tick {}",
            top_change.domain, tick
        )
    };

    WorldStateDelta {
        tick,
        summary,
        field_changes,
        affected_actors: agent_ids.to_vec(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_delta_with_military_action() {
        let delta = generate_delta(1, &["usa".to_string()], &["military_exercise".to_string()]);

        assert_eq!(delta.tick, 1);
        assert!(!delta.field_changes.is_empty());
        assert!(delta.summary.contains("conflict"));
        assert!(delta.affected_actors.contains(&"usa".to_string()));

        let conflict_change = delta.field_changes.iter().find(|c| c.domain == "conflict");
        assert!(conflict_change.is_some());
        assert!(conflict_change.unwrap().delta > 0.0);
    }

    #[test]
    fn generate_delta_with_diplomatic_action() {
        let delta = generate_delta(
            2,
            &["iran".to_string()],
            &["diplomatic_protest".to_string()],
        );

        let diplomacy_change = delta.field_changes.iter().find(|c| c.domain == "diplomacy");
        assert!(diplomacy_change.is_some());
        assert!(diplomacy_change.unwrap().delta > 0.0);
    }

    #[test]
    fn generate_delta_with_no_actions() {
        let delta = generate_delta(3, &[], &[]);

        assert_eq!(delta.tick, 3);
        assert!(delta.field_changes.is_empty());
        assert_eq!(delta.summary, "No significant field changes");
        assert!(delta.affected_actors.is_empty());
    }

    #[test]
    fn generate_delta_with_multiple_agents_and_actions() {
        let delta = generate_delta(
            4,
            &["usa".to_string(), "china".to_string()],
            &[
                "military_exercise".to_string(),
                "proportional counter-sanctions".to_string(),
            ],
        );

        assert_eq!(delta.affected_actors.len(), 2);
        assert!(delta.field_changes.len() >= 1);
    }

    #[test]
    fn world_state_delta_serialization_roundtrip() {
        let delta = WorldStateDelta {
            tick: 5,
            summary: "Conflict escalated".to_string(),
            field_changes: vec![FieldChange {
                region: "global".to_string(),
                domain: "conflict".to_string(),
                delta: 1.5,
            }],
            affected_actors: vec!["usa".to_string()],
        };

        let json = serde_json::to_string(&delta).unwrap();
        let deserialized: WorldStateDelta = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized, delta);
    }
}
